controller_list:
  - name: "/hand_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:

     - rotator2
     - finger1
     - finger2
     - finger3
      
  - name: "/arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint


